### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by DonaldTsang** [Coxxs/image-hide#2]
There is already
- a C++ version https://github.com/BlueCocoa/hoshizora and
- a C# version https://github.com/TomWildenhain/MagicPNG

Is it possible to use OpenCV, ImageMagick or FFMPEG to make a Python verion that is compatible?

**Comment by Coxxs** [comment]
Hackergame2019's official write up has a python version:
https://github.com/ustclug/hackergame2019-writeups/tree/master/official/%E7%99%BD%E4%B8%8E%E5%A4%9C
Code: https://github.com/ustclug/hackergame2019-writeups/blob/master/official/%E7%99%BD%E4%B8%8E%E5%A4%9C/src/run.py

You might need to tweak the code (or the picture), since the write up says: "The white background image should always be brighter than the black background image."
